[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = false # Ensures processing is enabled
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

[[redirects]]
  from = "http://*"
  to = "https://eskerdesigns.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.eskerdesigns.com/*"
  to = "https://eskerdesigns.com/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "public/assets/images",
    ".cache"
  ]